### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by JMcrafter26** [JM26NET/flipper-zero-evil-portal#1]
## If you are good in html and/or JavaScript, consider helping

Bugs:

- Doesn't submit the form
- Strange behavior on mobile (tested on iPhone)

**Comment by JMcrafter26** [comment]
@Roguemaster do you have html/js knowledge? Because this is very close to being finished.
Or if you know someone who could help, please let me know.

Thanks

**Comment by GauravKukreti** [comment]
Hey there 👋,

I'd be happy to help out! I'm experienced with HTML and JavaScript. Could you please provide more details about the what are you trying to do in the discordnano.html . This will help me better understand your project and how I might be able to contribute effectively.

Looking forward to collaborating with you!

**Comment by JMcrafter26** [comment]
Hi,
thank you for your offer to help, I am glad somebody wants to help out.

I am currently on vacation and don’t have a computer with me, but I will provide you some information:

There are some bugs I noticed, but the major two are: ~~the form does not submit when clicking on submit (the flipper does not receive any form data).~~ And second: On mobile (I only tested it on my iPhone using my flipper), the background image has 100% width wich means the user can/has to scroll horizontally and the input fields are aligned in the very center, as the form background is aligned on the left. -I will attach a screenshot at the end.

Some other bugs: 
- Darkreader (Darkmode) overwrites the background

Thank you again for your help, and if you have other question, both about the project and technically, feel free to ask.

@
![IMG_7287](https://github.com/JM26NET/flipper-zero-evil-portal/assets/77780772/09b51716-b4ea-47c5-aa9e-2ecd9ed10b3e)
![IMG_7288](https://github.com/JM26NET/flipper-zero-evil-portal/assets/77780772/430c8914-78c5-482b-ba21-294c2ff14ad9)


![BB018A0D-9268-42F6-96C4-75A990EB6131](https://github.com/JM26NET/flipper-zero-evil-portal/assets/77780772/7f6b4900-50bd-4e8c-a80e-a04781c55974)

**Comment by JMcrafter26** [comment]
And here are some technical details:

Goal: A very realistic Discord login screen with mobile and desktop compatibility and of course compatible with the evil portal for flipper zero.

HTML: A container and a form with the inputs, an empty div for the background

JS: Simple form validation system and submit. 
The other part of the JS: The long string is a gzipped svg of the (modified and minimized) discord background. The svg will then be extracted using the browser native api and then added to the empty div. -This needs to be done, as the character limit of 20k would be extended if the svg would not be gzipped.

**Comment by GauravKukreti** [comment]
Thanks
I think i can redesign and make it responsive. I will also remove the javascript for background svg because once its decrypted there is no need to decrypt again and again.
I will submit once I am done.

**Comment by JMcrafter26** [comment]
> Thanks
> 
> I think i can redesign and make it responsive. I will also remove the javascript for background svg because once its decrypted there is no need to decrypt again and again.
> 
> I will submit once I am done.

Is there a loop? I didn't noticed that, I am not a pro in JS and still learning. 
Thanks for your help, this will definitely speed things up!

**Comment by GauravKukreti** [comment]
I mean once svg is decrypted ,you have printed svg on console. So you can copy paste that in a svg file and then use it as a background.
I am working on it. Currently this is what i have build.
Tell me if you like it.
Current issues (maybe): 
- font style and size
- padding and margins

![Screenshot 2023-08-15 233700](https://github.com/JM26NET/flipper-zero-evil-portal/assets/73776421/74659723-32e0-4945-9764-bb9f4e69aeac)
![Screenshot 2023-08-15 233719](https://github.com/JM26NET/flipper-zero-evil-portal/assets/73776421/3206786a-a8d0-41fb-82d0-2df94fd6b1a2)

**Comment by GauravKukreti** [comment]
mobile view
![6260451035273344678_119](https://github.com/JM26NET/flipper-zero-evil-portal/assets/73776421/3396b1e2-be35-4b8d-ad57-4930c0599754)

**Comment by JMcrafter26** [comment]
> mobile view
> 
> ![6260451035273344678_119](https://github.com/JM26NET/flipper-zero-evil-portal/assets/73776421/3396b1e2-be35-4b8d-ad57-4930c0599754)
> 

@GauravKukreti 

And did I mention, that everything needs to be to be in one file, offline and under 20k characters? -This is the challenging part.

(Could you open a temporary pull request, so I can test it on an iPhone?)

**Comment by GauravKukreti** [comment]
Now size is around 6k because I hosted the svg online. If there is something wrong with my method, let me know I will try something else.

**Comment by JMcrafter26** [comment]
> Now size is around 6k because I hosted the svg online. If there is something wrong with my method, let me know I will try something else.

Unfortunately this is not possible. 
Like I said previously, the evil portal project for the flipper zero has some big limitations: Everything must be available offline AND in the one html file, no external images or anything, also the character limit is 20k. This was really tricky, so I decided to use the gzip method and I think this is the best solution to this problem.
